trigger:
  branches:
    include:
    - master
    - 'validate/*'
    - 'release/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  codecov_token: 04802333-ccec-405f-a010-692b5c5a90c7
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- template: azure-pipelines/build.yml
